# Generated by Django 3.2.12 on 2022-04-06 09:46

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=pathlib.PureWindowsPath('F:/developer/repositories/my-drf-project/my-todo-site-on-drf/backend/media'), upload_to='users/%Y/%m/%d/', verbose_name='фото'),
        ),
    ]
