# Generated by Django 3.2.12 on 2022-04-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user.png', upload_to='users/%Y/%m/%d/', verbose_name='фото'),
        ),
    ]
