# Generated by Django 3.2.12 on 2022-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('A', 'активна'), ('I', 'неактивна'), ('V', 'формируется'), ('C', 'закрыто')], default='A', max_length=1, verbose_name='статус заметки'),
        ),
    ]
