# Generated by Django 3.2.12 on 2022-04-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('A', 'активна'), ('I', 'неактивна'), ('V', 'формируется'), ('C', 'закрыто')], default='A', max_length=1, verbose_name='расширенный статус'),
        ),
    ]
